services:
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
    instagram:
        class: Site\MainBundle\Instagram\Instagram
        arguments: ['@service_container', '@doctrine.orm.entity_manager']

#    site_main.example:
#        class: Site\MainBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
