# src/Site/Bundle/MainBundle/Resources/config/validation.yml
Site\MainBundle\Entity\News:
    properties:
        title:
            - NotBlank:
                message: "backend.news.validation.title"
            - Length:
                max: 100
        date:
            - NotBlank:
                message: "backend.news.validation.date"
        type:
            - NotBlank:
                message: "backend.news.validation.type"

Site\MainBundle\Entity\Announcement:
    properties:
        title:
            - NotBlank:
                message: "backend.announcement.validation.title"
            - Length:
                max: 100
        date:
            - NotBlank:
                message: "backend.announcement.validation.date"

Site\MainBundle\Entity\Page:
    properties:
        title:
            - NotBlank:
                message: "backend.page.validation.title"
            - Length:
                max: 100
        position:
            - Type:
                type: integer
                message: "backend.page.validation.position_integer"
            - GreaterThan:
                value: -1
                message: "backend.page.validation.position_min"
            - NotBlank:
                message: "backend.page.validation.position"

Site\MainBundle\Entity\Partners:
    properties:
        position:
            - Type:
                type: integer
                message: "backend.partners.validation.position_integer"
            - GreaterThan:
                value: -1
                message: "backend.partners.validation.position_min"
            - NotBlank:
                message: "backend.partners.validation.position"
        name:
            - NotBlank:
                message: "backend.partners.validation.name"
            - Length:
                max: 100
        link:
            - Url:
                message: "backend.partners.validation.link_not_valid"

Site\MainBundle\Entity\Slider:
    properties:
        date:
            - NotBlank:
                message: "backend.slider.validation.date"


Site\MainBundle\Entity\Event:
    properties:
        name:
            - NotBlank:
                message: "backend.event.validation.name"
        tour:
            - Type:
                type: integer
                message: "backend.event.validation.tour_integer"
            - GreaterThan:
                value: -1
                message: "backend.event.validation.tour_min"
        datetime:
            - NotBlank:
                message: "backend.event.validation.datetime"
        numberGoals:
            - Type:
                type: integer
                message: "backend.event.validation.number_goals_integer"
            - GreaterThan:
                value: -1
                message: "backend.event.validation.number_goals_min"
        numberYellowCards:
            - Type:
                type: integer
                message: "backend.event.validation.number_yellow_cards_integer"
            - GreaterThan:
                value: -1
                message: "backend.event.validation.number_yellow_cards_min"

Site\MainBundle\Entity\Team:
    properties:
        name:
            - NotBlank:
                message: "backend.team.validation.name"

Site\MainBundle\Entity\Player:
    properties:
        firstname:
            - NotBlank:
                message: "backend.player.validation.firstname"
            - Length:
                max: 50
        secondname:
            - Length:
                max: 50
        birthPlace:
            - Length:
                max: 100
        nationality:
            - Length:
                max: 50
        amplua:
            - Length:
                max: 50
        height:
            - Length:
                max: 50
        weight:
            - Length:
                max: 50
        firstCoach:
            - Length:
                max: 50

Site\MainBundle\Entity\Media:
    properties:
        title:
            - NotBlank:
                message: "backend.media.validation.title"

Site\MainBundle\Entity\Director:
    properties:
        name:
            - NotBlank:
                message: "backend.director.validation.name"

Site\MainBundle\Entity\Baner:
    properties:
        link:
            - Url:
                message: "backend.baner.validation.link_not_valid"

Site\MainBundle\Entity\GoalEvent:
    properties:
        score:
            - NotBlank:
                message: "backend.goal_event.validation.score"