backend_instagram_index:
    path:     /
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:index" }

backend_instagram_index_ajax:
    path:     /ajax/next
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:ajaxIndex" }
    methods: [POST]

backend_instagram_new:
    path:     /new
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:new" }
    methods: [POST]

backend_instagram_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:delete" }
    methods:  [POST, DELETE]
