backend_instagram_index_change:
    path:     /change
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:change" }
    methods: [POST]

backend_instagram_index:
    path:     /{tag}
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:index", tag: 'fcrossiyanka' }

backend_instagram_index_ajax:
    path:     /ajax/next/{tag}
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:ajaxIndex", tag: 'fcrossiyanka' }
    methods: [POST]

backend_instagram_new:
    path:     /new
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:new" }
    methods: [POST]

backend_instagram_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteMainBundle:Backend/Instagram:delete" }
    methods:  [POST, DELETE]
