backend_dashboard:
    path:     /
    defaults: { _controller: "SiteMainBundle:Backend/Dashboard:index" }

backend_page:
    resource: "@SiteMainBundle/Resources/config/routing/backend/page.yml"
    prefix: /page

backend_partners:
    resource: "@SiteMainBundle/Resources/config/routing/backend/partners.yml"
    prefix: /partners

backend_slider:
    resource: "@SiteMainBundle/Resources/config/routing/backend/slider.yml"
    prefix: /slider

backend_news:
    resource: "@SiteMainBundle/Resources/config/routing/backend/news.yml"
    prefix: /news

backend_announcement:
    resource: "@SiteMainBundle/Resources/config/routing/backend/announcement.yml"
    prefix: /announcement

backend_event:
    resource: "@SiteMainBundle/Resources/config/routing/backend/event.yml"
    prefix: /event

backend_team:
    resource: "@SiteMainBundle/Resources/config/routing/backend/team.yml"
    prefix: /team

backend_player:
    resource: "@SiteMainBundle/Resources/config/routing/backend/player.yml"
    prefix: /player

backend_media:
    resource: "@SiteMainBundle/Resources/config/routing/backend/media.yml"
    prefix: /media

backend_director:
    resource: "@SiteMainBundle/Resources/config/routing/backend/director.yml"
    prefix: /director

backend_baner:
    resource: "@SiteMainBundle/Resources/config/routing/backend/baner.yml"
    prefix: /baner

backend_instagram:
    resource: "@SiteMainBundle/Resources/config/routing/backend/instagram.yml"
    prefix: /instagram

SitePollBundle_backend:
    resource: "@SitePollBundle/Resources/config/routing/backend.yml"
    prefix: /poll