frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_partners:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/partners.yml"
    prefix: /partners

frontend_news:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news.yml"
    prefix: /novosti

frontend_event:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/event.yml"
    prefix: /turniry

frontend_page:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/page.yml"