frontend_news_index:
    path:     /{type}
    defaults: { _controller: "SiteMainBundle:Frontend/News:index" }
    requirements:
      type: events|interviews|opinion

frontend_news_one:
    path:     /{type}/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/News:one" }
    requirements:
      type: events|interviews|opinion